# Generated by Django 4.0.8 on 2022-12-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
