# Generated by Django 4.0.8 on 2022-12-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_remove_publicacion_categoria_publicacion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(default=True, upload_to='publicaciones'),
        ),
    ]
