# Generated by Django 4.0.8 on 2022-12-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_publicacion_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha',
            new_name='fecha_agregado',
        ),
        migrations.AddField(
            model_name='comentario',
            name='name',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comentario',
            name='publicacion',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='publicaciones.publicacion'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
