# Generated by Django 4.0.8 on 2022-12-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0008_delete_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='detalle',
        ),
    ]
