# Generated by Django 4.0.8 on 2022-12-22 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0009_remove_publicacion_detalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ('-published',)},
        ),
        migrations.AddField(
            model_name='publicacion',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
