# Generated by Django 4.0.8 on 2022-12-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0010_alter_publicacion_options_publicacion_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ('-fecha',)},
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='published',
        ),
    ]
