# Generated by Django 4.0.8 on 2022-12-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0011_alter_publicacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ('-titulo',)},
        ),
    ]
