# Generated by Django 4.0.8 on 2022-12-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0015_alter_publicacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={},
        ),
    ]
