# Generated by Django 4.0.8 on 2022-12-20 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre_categoria',
            new_name='nombre',
        ),
    ]
