# Generated by Django 4.0.8 on 2022-12-20 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('publicaciones', '0002_publicacion_activa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='activa',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria'),
        ),
    ]
