# Generated by Django 4.0.8 on 2022-12-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_rename_nombre_categoria_categoria_nombre'),
        ('publicaciones', '0003_remove_publicacion_activa_publicacion_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='categoria',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.ManyToManyField(to='categorias.categoria'),
        ),
    ]
