# Generated by Django 4.0.8 on 2022-12-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0007_remove_comentario_name_comentario_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
